const express = require('express');
const mongoose = require('mongoose');
const app = express();
const cors = require ('cors');
const path = require('path');
const bodyParser = require('body-parser');
app.use(bodyParser.urlencoded({ extended: true }))
app.use(bodyParser.json())
// const express = require('express');
app.use(cors());
const homeControll =  require('./controllers/HomeController');
const ExamController = require('./controllers/ExamController');
const AdminCon = require('./controllers/AdminController');
const StudentController = require('./controllers/StudentController');
const Admin = new AdminCon(app,path); 
const Home =  new homeControll(app,path);
const Exams =  new ExamController(app,path);
const Student = new StudentController(app,path);
Student.getStudents();
Student.addStudent();
Admin.loginAdmin();
Admin.AdminLogin();
Admin.addAdmin();
Admin.uploadAdmin();
Admin.validateAdmin();
Admin.verify();
Admin.adminAddScore();
Admin.dashboard();
Exams.startExam();
Home.AppListening ();
const port = 3000;
Exams.addQuestion();
Exams.saveQuestion();
Exams.showExam();
Exams.SubmitExam();
Exams.addScore();
Home.goHome();
app.listen(port,function(){
console.log('application is running on port',port);
});